[theme]
base="dark"
primaryColor="#1DB954"  # Exemplo: verde Spotify, pode mudar para sua cor preferida
backgroundColor="#000000"
secondaryBackgroundColor="#121212"
textColor="#FFFFFF"
font="sans serif"
